### ISSUE TITLE
Timeout/connection issues with `get_iter`

### ISSUE THREAD

**Issue by mkirzon** [gtalarico/airtable-python-wrapper#46]
I'm running into an issue where using `get_iter` on large tables (eg 40k+rows) ends up having connection / timeout issues after 30m-1hr of looping through records. This happens consistently. Right after it errors, I can restart the script and it resumes from the same spot without error for another ~30min. 

Is there any special error handling you recommend implementing to re-authenticate or prevent this? I'm attaching the python error below -
```
Traceback (most recent call last):
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\util\connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\mkirz\Miniconda3\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\connection.py", line 314, in connect
    conn = self._new_conn()
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001FE27A98D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.airtable.com', port=443): Max retries exceeded with url: /v0/hidingAPIkey/People/hidingkey (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FE27A98D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/mkirz/Documents/Development Work/Github/diffbot-queries/Main_dev.py", line 90, in <module>
    record_mod = airtbl_ppl.update(airtbl_ppl_id, new_record, typecast=False)
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\airtable\airtable.py", line 418, in update
    return self._patch(record_url, json_data={"fields": fields, "typecast": typecast})
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\airtable\airtable.py", line 197, in _patch
    return self._request('patch', url, json_data=json_data)
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\airtable\airtable.py", line 183, in _request
    json=json_data)
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mkirz\Miniconda3\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.airtable.com', port=443): Max retries exceeded with url: /v0/hidingAPIkey/People/hidingkey (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FE27A98D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Process finished with exit code 1
```

**Comment by bpeterso2000** [comment]
> Right after it errors, I can restart the script and it resumes from the same spot without error for another ~30min.

Since it continues where you left off you could use the backoff decorator in https://pypi.org/project/backoff/  The docs include an example of using it to retry requests Connection Errors.

**Comment by mkirzon** [comment]
@bpeterso2000 nice suggestion. Would this require updating the API or should I be able to decorate my high level calls to `get_iter`? 

In my main script, I have 2 for loops:
```
for page in airtbl_ppl.get_iter(sort=['Name'], formula=airtbl_formula):
  for index, record in enumerate(page, start=1):
    [actual code]
```

Where in that structure would I be able to decorate with backoff?

**Comment by bpeterso2000** [comment]
If it is continuing from where it left off when you rerun the script then you should be able to put all of the above code into a single function and decorate it.

**Comment by gtalarico** [comment]
Official Airtable Js has backoff included in the library
https://github.com/Airtable/airtable.js/blob/master/lib/run_action.js#L10

**Comment by gtalarico** [comment]
I reviewed this and I think instead of adding a dependency or backoff logic users can easily add it as needed:

```python
from airtable import Airtable
import backoff
from requests.exceptions import ConnectTimeout

table = Airtable("appNtnZ99fkL1cByn", "entries")
get_all = backoff.on_exception(backoff.expo, ConnectTimeout, max_tries=5)(table.get_all)
get_with_backoff()
``
