### ISSUE TITLE
Bug in search & match functions

### ISSUE THREAD

**Issue by ncbaratta** [gtalarico/airtable-python-wrapper#55]
I'm trying to add new contacts if the email isn't already in Airtable.

```
outreach = Airtable(key, teachtable, api_key='MINE')
airtable = outreach.get_all(view='All Teachers', fields=['Email'])

if airtable.match('Email', email):
        print("Found in database ",email)
    else:
        airtable.insert({'First': first, 'Last': last, 'Email': email, 'Phone': phone, 'Title': title, 'School': school_id})
        print(first,last, 'added')
```

But I keep getting this error:

```
Traceback (most recent call last):
  File "rrisd2019-air.py", line 51, in <module>
    if airtable.match('Email', email):
AttributeError: 'list' object has no attribute 'match'
```
I tried using search instead ...
```
if outreach.match('Email', email):
        print("Found in database ",email)
    else:
        airtable.insert({'First': first, 'Last': last, 'Email': email, 'Phone': phone, 'Title': title, 'School': school_id})
        print(first,last, 'added')
```
but got the following:
```
Traceback (most recent call last):
  File "rrisd2019-air.py", line 51, in <module>
    if outreach.match('Email', email):
  File "/Library/Python/2.7/site-packages/airtable/airtable.py", line 304, in match
    for record in self.get_all(**options):
  File "/Library/Python/2.7/site-packages/airtable/airtable.py", line 273, in get_all
    for records in self.get_iter(**options):
  File "/Library/Python/2.7/site-packages/airtable/airtable.py", line 237, in get_iter
    data = self._get(self.url_table, offset=offset, **options)
  File "/Library/Python/2.7/site-packages/airtable/airtable.py", line 175, in _get
    return self._request("get", url, params=processed_params)
  File "/Library/Python/2.7/site-packages/airtable/airtable.py", line 171, in _request
    return self._process_response(response)
  File "/Library/Python/2.7/site-packages/airtable/airtable.py", line 161, in _process_response
    raise requests.exceptions.HTTPError(err_msg)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/MINETeacher Outreach?filterByFormula={Email}=email@email.com (Decoded URL) [Error: {u'message': u'The formula for filtering records is invalid: Invalid formula. Please check your formula text.', u'type': u'INVALID_FILTER_BY_FORMULA'}]
```

**Comment by ncbaratta** [comment]
https://codepen.io/airtable/pen/rLKkYB - airtable API url encoder says url should look like
```
https://api.airtable.com/v0/appnmdmRdZvjesFeb/Teacher%20Outreach?fields%5B%5D=Email&filterByFormula=abi.perroni%40austinisd.org&view=All+Teachers
```
error says

```
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.airtable.com/v0/appnmdmRdZvjesFeb/Teacher Outreach?filterByFormula={Email}=abi.perroni@austinisd.org (Decoded URL) [Error: {u'message': u'The formula for filtering records is invalid: Invalid formula. Please check your formula text.', u'type': u'INVALID_FILTER_BY_FORMULA'}]
```
So, is this a bug?

**Comment by gtalarico** [comment]
Could be an encoding issue.
Sorry I havent had time to look into this

**Comment by dsomel21** [comment]
I am getting this to

**Comment by gtalarico** [comment]
```
airtable = outreach.get_all(view='All Teachers', fields=['Email'])

if airtable.match('Email', email): # airtable is overwritten as a `list()` 
   ...
```

422 issue is likely a mismatch between your data and the table. 
Recent release include 422 error in exception and should help
